### ISSUE TITLE
facet titled "University" doesn't match the data within institution_label_ssim

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-webapp#105]
Can we change it to "Institution"?

Some values that don't match: "Childrens Hospital Oakland", "VA Palo Alto Health Care", "Teva Branded Pharmaceut Prod R&D"

**Comment by peetucket** [comment]
Yes, change to institution

**Comment by mjgiarlo** [comment]
Waffle mess-up. Closing again.
