### ISSUE TITLE
Webapp is unavailable

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-webapp#24]
it is giving:
```
503 Service Temporarily Unavailable
```

**Comment by aaron-collier** [comment]
This is due to moving the SOLR instance into the VPC and setting up the security groups. It should be resolved shortly.

**Comment by aaron-collier** [comment]
Back online (with a bit less SOLR data since it was a reset from the AMI)

**Comment by jcoyne** [comment]
🎉 Thanks Aaron 🥇
