### ISSUE TITLE
Blacklight can't route to concept with certain characters in identifiers

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-webapp#28]
https://rialto.dev.sul.stanford.edu/catalog/http%3A%2F%2Fsul.stanford.edu%2Frialto%2Fconcepts%2Fepidemiology%2C_gene-environment%2C_perinatal%2C_pediatric%2C_preterm_birth%2C_birth_defects

This routes correctly, and the object exists in solr, but it can't see it.

**Comment by jcoyne** [comment]
```ruby
search_service = Blacklight::SearchService.new(CatalogController.blacklight_config, {})
id= 'http://sul.stanford.edu/rialto/concepts/epidemiology,_gene-environment,_perinatal,_pediatric,_preterm_birth,_birth_defects'
search_service.fetch(id)
```

**Comment by peetucket** [comment]
ETL will have concepts that have identifiers that do not have commas -- adjusted in ETL code

This is only currently a problem with the test data
