### ISSUE TITLE
View grant data from SeRA API in browse section on website

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/rialto-webapp#98]
blocked by sul-dlss/rialto#274
blocked by sul-dlss-labs/rialto-derivatives#108

**Comment by jcoyne** [comment]
<img width="1058" alt="screen shot 2018-10-29 at 9 16 34 am" src="https://user-images.githubusercontent.com/92044/47655634-6fdc1000-db5b-11e8-9054-5dcf1047b49f.png">

The grant data that is indexed is displaying on the website. (See https://rialto.dev.sul.stanford.edu/#/item/http:%2F%2Fsul.stanford.edu%2Frialto%2Fgrants%2F136018)
